version: "3.9"
services:
  tgrentalbot:
    build: .
    container_name: tgrentalbot
    command: python -u main.py
    env_file: .env
    environment:
      TZ: Asia/Singapore
    restart: unless-stopped
    networks:
      - wanatring

networks:
  wanatring:
    driver: bridge